name: Keystone Framework (Fixed)
description: Keystone Framework server setup with fixed setup.sql
version: 1.0
repository: https://github.com/Tobbe0223/keystonefixed111

tasks:
  - task: download_github
    url: https://github.com/Tobbe0223/keystonefixed111/archive/refs/heads/main.zip
    dest: resources/KeystoneFramework
    unzip: true

  - task: query_database
    file: resources/KeystoneFramework/resources/[txAdmin]/setup.sql
